### ISSUE TITLE
🐛 Bug Report: Prompt ChatGPT Python Template not rendering page

### ISSUE THREAD

**Issue by codewithkushagra** [appwrite/templates#220]
### 👟 Reproduction steps
- Deploy an instance of Prompt ChatGPT template using appwrite function.
- Follow the deployment link and you will find that HTML page is not being rendered

### Reason for issue
- The Content-Type received is `text/plain`
- Where as for rendering HTML content it should have been `text/html`
<img width="411" alt="Screenshot 2023-10-06 at 2 48 56 AM" src="https://github.com/appwrite/templates/assets/72088481/df71a1a9-204b-41ea-8be3-8e2b95565e2b">

### Suggested Solution

Here in the current code context is parsing content-type as Content-Type which is causing this issue

```
if context.req.method == "GET":
        return context.res.send(
            get_static_file("index.html"),
            200,
            {
                "Content-Type": "text/html; charset=utf-8"
            }
        )
```

To correct this we can change the Content-Type to content-type in the code that is 

```
if context.req.method == "GET":
        return context.res.send(
            get_static_file("index.html"),
            200,
            {
                "content-type": "text/html; charset=utf-8"
            }
        )
```

### 👍 Expected behavior

The expected behavior should have been the rendered HTML page like 

<img width="1237" alt="Screenshot 2023-10-06 at 2 57 40 AM" src="https://github.com/appwrite/templates/assets/72088481/2c3d1a0a-0479-4d89-8d27-77f2a8141212">

### 👎 Actual Behavior

But the actual current behavior is showing unrendered raw HTML

<img width="640" alt="Screenshot 2023-10-06 at 2 58 53 AM" src="https://github.com/appwrite/templates/assets/72088481/8a6ae75f-14eb-46eb-92aa-ac2f2d459f94">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite version  1.4.4, I haven't customized it any ways

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by codewithkushagra** [comment]
@Haimantika I have found this issue while setting up and testing the platform can you please assign me this issue, so that I can raise a PR for it.

**Comment by loks0n** [comment]
Hey @codewithkushagra,
I've assigned you to the issue.
Feel free to open a PR for it

**Comment by codewithkushagra** [comment]
okay, Thank you @loks0n I will create a PR for this

**Comment by codewithkushagra** [comment]
@loks0n I have made the PR here: https://github.com/appwrite/templates/pull/224 
Can you please review it, and if it looks good to you can merge it
