### ISSUE TITLE
🚀 Feature: Add PDF Generator in node-typescript

### ISSUE THREAD

**Issue by AnubhavChakrabortynits** [appwrite/templates#237]
### 🔖 Feature description

This Will be a node-typescript version of the generate PDF in vanilla node js.

### 🎤 Pitch

This feature is amongst the ones that are mentioned in the list and has not been implemented yet. The (non-typescript) version of the feature already exists. So I feel, the typescript version should also be implemented.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by AnubhavChakrabortynits** [comment]
@Haimantika will please assign me this issue. I would love to work on it. I have developed a PDF generator before as well in one of my personal projects and I am confident enough to implement this feature.

**Comment by Kunal-Ladhani** [comment]
@Haimantika worked with pdf-generator that converted excel, csv to pdf. will be fairly easy to deliver. please assign to me

**Comment by loks0n** [comment]
Hi, thank you for your interest in participating in Hacktoberfest!

We really appreciate your enthusiasm.

So this year, we’re focused on quality contributions. This doesn’t just mean we want quality code from contributors; we also want to foster a quality relationship with the contributors through extensive reviews and support so they can tackle more meaningful and difficult projects.

With that said, we have a small team with limited capacity. So we’re careful about how many active issues we post for Hacktoberfest, so we can review and support each contributor adequately. 

That said, if you find a reasonably sized issue on the Appwrite repo that you’d like to tackle, you can pitch your solution to the problem, and we will review and label the issue Hacktoberfest if it makes sense.

We also have community rewards every month for everything from cool projects, helpful community members, and even just sick memes. If you’re interested in contributing, being an active community member is also a good way to go.
