### ISSUE TITLE
🐛 Bug Report: Swift Template does not compile

### ISSUE THREAD

**Issue by atacan** [appwrite/templates#261]
### 👟 Reproduction steps

Open the `swift/starter` folder in Xcode

### 👍 Expected behavior

- The code compiles
- Witt the current `Package.swift` content, the folder structure should be `Sources/swift-function/main.swift`

### 👎 Actual Behavior

- Folder and file structure is wrong
- There are no types named `RuntimeContext` and `RuntimeOutput`

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

AppWrite 1.4.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

![ScrShot 2024-01-02 at 13 41 16@2x](https://github.com/appwrite/templates/assets/765873/e2e67f24-e458-46a7-a52f-cb0214c43feb)

**Comment by RV784** [comment]
I don't think you can build Appwrite functions locally :) They're a file depended upon by the Appwrite Functions runtimes. 
Have you deployed the starter function to your Appstore instance? For me it works that way.
