### ISSUE TITLE
🐛 Bug Report: Not able to join Discord

### ISSUE THREAD

**Issue by hdhaliwa** [appwrite/templates#265]
### 👟 Reproduction steps

![Screenshot 2024-02-22 090653](https://github.com/appwrite/templates/assets/27665205/e0395ca2-5eeb-4071-9c18-f9f55182c8e9)
![Screenshot 2024-02-22 090714](https://github.com/appwrite/templates/assets/27665205/e5f3750f-e049-4248-8f31-f3d97dae5bcc)
![Screenshot 2024-02-22 090732](https://github.com/appwrite/templates/assets/27665205/72413bb1-2289-45ef-aae4-a12928aa1d9f)
When i give my email, i do not get any invitation from Discord to join.

### 👍 Expected behavior

I should be getting an invite to join the discord community.

### 👎 Actual Behavior

I am not getting an invite to join the discord community.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment]
@hdhaliwa - can you provide reproduction steps on where you're accessing the invite? Does going to [appwrite.io/discord](appwrite.io/discord) directly yield the same results? 

I am not receiving the same results as you are, so any additional insights on how you're accessing this will help:

![image](https://github.com/appwrite/templates/assets/23223867/21b53bea-4e16-4754-94d8-b31d581cf28e)

**Comment by hdhaliwa** [comment]
thank you @EVDOG4LIFE I am able to resolve this issue. I went to discord.com and downloaded the exe for windows, and then registered with my email.
